feat: enable/disable analytics programmatically
allboatsrise/expo-marketingcloudsdk pull request #47
Opened 2024-10-23 17:27 UTC by pehagg

This PR adds support for `isAnalytics`, `enableAnalytics`, and `disableAnalytics`, resolving #46. 

My local linter setup seems to have reformatted the code as there's no linter rules set for the repo. Please let me know if you want me to revert the formatting changes.

2024-10-23 18:01 UTC, andrejpavlovic requested changes
Minor issue with `enableAnalytics` in Android. Please revert the code formatting just so we can keep better track of changes specific to this PR.

2024-10-23 18:01 UTC, andrejpavlovic commented on android/src/main/java/expo/modules/marketingcloudsdk/ExpoMarketingCloudSdkModule.kt
> +        promise.resolve(mp.analyticsManager.enableAnalytics())
```suggestion
        promise.resolve(mp.analyticsManager.areAnalyticsEnabled())
```

2024-10-24 05:25 UTC, pehagg commented on android/src/main/java/expo/modules/marketingcloudsdk/ExpoMarketingCloudSdkModule.kt
> +        promise.resolve(mp.analyticsManager.enableAnalytics())
Good catch, didn't test this case.

2024-10-24 05:32 UTC, pehagg commented
Formatting and change request addressed. There's still some minor formatting differences, couldn't get prettier to co-operate to fully match the existing style.

2024-10-25 17:59 UTC, closed without merging

2024-10-25 18:06 UTC, andrejpavlovic commented
Released in 51.0.6